"""
DDL generation and schema-drift detection for the ingestion pipeline.

Design philosophy:
  - All data columns default to TEXT (bronze/landing layer — no type casting).
  - Three standard metadata columns are appended to every table:
        _ingested_at  TIMESTAMPTZ   when the row was loaded
        _source_file  TEXT          name of the originating CSV file
        _row_hash     TEXT          MD5 of all data values (for dedup / audit)
  - DDL is written to a human-readable .sql file BEFORE being applied, so
    the engineering team can review / version-control it.
  - An index on _row_hash is created alongside the table (IF NOT EXISTS) to
    make incremental dedup lookups fast.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

import pandas as pd
import psycopg2
from psycopg2 import sql
from psycopg2.extensions import connection as PgConnection

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Conservative pandas → PostgreSQL type mapping
# For a bronze layer, TEXT is the safest fallback.  Only unambiguously
# numeric pandas dtypes are promoted to native Postgres numeric types so that
# downstream silver-layer queries don't have to cast everything.
# ---------------------------------------------------------------------------
_DTYPE_TO_PG: dict[str, str] = {
    "int8":         "BIGINT",
    "int16":        "BIGINT",
    "int32":        "BIGINT",
    "int64":        "BIGINT",
    "uint8":        "BIGINT",
    "uint16":       "BIGINT",
    "uint32":       "BIGINT",
    "uint64":       "NUMERIC(20,0)",   # BIGINT can overflow for uint64
    "float16":      "DOUBLE PRECISION",
    "float32":      "DOUBLE PRECISION",
    "float64":      "DOUBLE PRECISION",
    "bool":         "BOOLEAN",
    "object":       "TEXT",
    "string":       "TEXT",
    "category":     "TEXT",
    "datetime64":   "TIMESTAMP",
    "datetime64[ns]": "TIMESTAMP",
}

# Metadata columns appended to every table
_METADATA_DDL = [
    "_ingested_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()",
    "_source_file  TEXT         NOT NULL",
    "_row_hash     TEXT         NOT NULL",
]


def _pg_type(col_series: pd.Series) -> str:
    """
    Map a pandas Series to a conservative Postgres column type.

    Rule: only columns that pandas natively infers as an integer dtype (int8
    through int64, uint*, or pandas nullable Int*) become BIGINT.  If pandas
    chose float64, that means either the column genuinely has fractional
    values OR it has NaN (pandas has no nullable-int dtype by default, so it
    promotes int-with-NaN to float64).  In both cases the CSV will store
    values like "276.0" — which Postgres cannot COPY into BIGINT — so we
    keep them as DOUBLE PRECISION.

    Never do "int-like float" promotion: the DDL is sniffed from a sample,
    the data is loaded as raw strings via COPY, and any ".0" suffix will
    cause a hard COPY failure on a BIGINT column.
    """
    dtype = col_series.dtype
    key = str(dtype)

    # Pandas nullable integer types (Int8, Int16, Int32, Int64, UInt*)
    if key.startswith("Int") or key.startswith("UInt"):
        return "BIGINT"

    return _DTYPE_TO_PG.get(key, "TEXT")


def generate_ddl(
    schema: str,
    table: str,
    sample: pd.DataFrame,
) -> str:
    """
    Generate a CREATE TABLE IF NOT EXISTS DDL string for *schema.table*.

    Parameters
    ----------
    schema : str
        Target Postgres schema name.
    table : str
        Target table name.
    sample : pd.DataFrame
        A representative sample of the CSV (header + a few rows) used only
        for type inference.  The actual data is not written here.

    Returns
    -------
    str
        A multi-statement DDL string (CREATE TABLE + CREATE INDEX).
    """
    col_defs: list[str] = []

    for col in sample.columns:
        pg_type = _pg_type(sample[col])          # pass Series, not just dtype
        col_defs.append(f'    "{col}" {pg_type}')

    # Append metadata columns (same 4-space indent as data columns)
    for meta in _METADATA_DDL:
        col_defs.append(f"    {meta}")

    cols_block = ",\n".join(col_defs)

    # Build DDL with consistent indentation — no textwrap.dedent so that
    # the cols_block (already indented) is not stripped.
    ddl = (
        f"-- Auto-generated by Credit Arbiter ingestion pipeline.\n"
        f"-- Review before applying.  Do NOT edit the _metadata columns.\n"
        f"-- Source table: {schema}.{table}\n"
        f"\n"
        f'CREATE TABLE IF NOT EXISTS "{schema}"."{table}" (\n'
        f"{cols_block}\n"
        f");\n"
        f"\n"
        f"-- Index used by incremental dedup lookups (hash-equality scan)\n"
        f'CREATE INDEX IF NOT EXISTS "{table}__row_hash_idx"\n'
        f'    ON "{schema}"."{table}" (_row_hash);\n'
    )
    return ddl


def write_ddl_file(ddl: str, table: str, ddl_dir: Path) -> Path:
    """
    Persist the DDL string to *ddl_dir/<table>.sql* for human review.

    Returns the path of the written file.
    """
    ddl_dir.mkdir(parents=True, exist_ok=True)
    out_path = ddl_dir / f"{table}.sql"
    out_path.write_text(ddl, encoding="utf-8")
    logger.info("DDL written -> %s", out_path)
    return out_path


def apply_ddl(
    conn: PgConnection,
    ddl: str,
    table: str,
    *,
    schema: str = "raw",
    drop_first: bool = False,
) -> None:
    """
    Execute the DDL string against the open connection.

    Parameters
    ----------
    drop_first : bool
        When True, issue ``DROP TABLE IF EXISTS ... CASCADE`` before the
        CREATE TABLE statement.  Use in ``full_refresh`` mode so that any
        stale column types from a previous DDL run are replaced.
        Safe because full_refresh reloads all rows from the CSV anyway.
    """
    if drop_first:
        with conn.cursor() as cur:
            cur.execute(
                sql.SQL("DROP TABLE IF EXISTS {}.{} CASCADE").format(
                    sql.Identifier(schema), sql.Identifier(table)
                )
            )
        conn.commit()
        logger.info("Dropped existing table '%s'.'%s' (full_refresh).", schema, table)

    statements = [s.strip() for s in ddl.split(";") if s.strip()]
    with conn.cursor() as cur:
        for stmt in statements:
            try:
                cur.execute(stmt)
            except psycopg2.errors.DuplicateObject:
                # Index already exists — harmless in IF NOT EXISTS context
                conn.rollback()
                logger.debug("Object already exists (skipped): %.120s", stmt)
                cur = conn.cursor()
    conn.commit()
    logger.info("DDL applied for '%s'.", table)


def get_existing_columns(
    conn: PgConnection,
    schema: str,
    table: str,
) -> dict[str, str]:
    """
    Return {column_name: data_type} for an existing table.
    Returns an empty dict if the table does not yet exist.
    """
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT column_name, data_type
            FROM   information_schema.columns
            WHERE  table_schema = %s
              AND  table_name   = %s
            ORDER  BY ordinal_position
            """,
            (schema, table),
        )
        return {row[0]: row[1] for row in cur.fetchall()}


def check_schema_drift(
    existing_columns: dict[str, str],
    incoming_columns: list[str],
    table: str,
) -> list[str]:
    """
    Compare the live table's columns against what the incoming CSV provides.

    Returns a list of human-readable warning strings (empty list = no drift).
    Metadata columns (_ingested_at, _source_file, _row_hash) are excluded
    from the diff since they don't come from the CSV.
    """
    _meta = {"_ingested_at", "_source_file", "_row_hash"}
    db_names = set(existing_columns.keys()) - _meta
    csv_names = set(incoming_columns)

    warnings: list[str] = []

    new_cols = csv_names - db_names
    if new_cols:
        warnings.append(
            f"[SCHEMA DRIFT] {table}: CSV has new columns not in DB table — "
            f"{sorted(new_cols)}.  "
            f"Run --ddl-only after updating sources.yaml to add them."
        )

    dropped_cols = db_names - csv_names
    if dropped_cols:
        warnings.append(
            f"[SCHEMA DRIFT] {table}: DB table has columns absent from CSV — "
            f"{sorted(dropped_cols)}.  "
            f"Those columns will remain NULL for this load."
        )

    return warnings
